---
contentdir: content
layoutdir: layouts
publishdir: public
baseurl: http://skulsky.ru/
title: "Алексей Скульский"
canonifyurls: true
theme: skulsky
paginate: 5
pluralizelisttitles: false
params:
  about: "В толковом словаре Ушакова понятие «текст» определяется как «всякая запечатленная
    в письменности или в памяти речь, написанные или сказанные кем-н. слова, к-рые
    можно воспроизвести, повторить в том же виде».  Именно как к текстам я отношусь
    к тому, что пишу и публикую на этом сайте. Литературу оставим писателям. Эти тексты
    и есть моя биография."
  description: "Тексты, рассказы, зарисовки и размышления"
taxonomies:
  category: categories
